### ISSUE TITLE
Issues with formatting and screenshots in the Android demo

### ISSUE THREAD

**Issue by jeffxtang** [pytorch/executorch#1053]
In the demo [here](https://github.com/pytorch/executorch/tree/main/examples/demo-apps/android/ExecuTorchDemo):

![image](https://github.com/pytorch/executorch/assets/535090/5c29ce31-4249-439c-a7a5-41452bc1d31a)

![image](https://github.com/pytorch/executorch/assets/535090/5f6403ee-2664-4102-938b-dc32edea4987)

**Comment by dbort** [comment]
Thanks for pointing this out, @jeffxtang. This is a side-effect of the way that we manage our docs; in this case, the .md file is rendered on the docs website at https://pytorch.org/executorch/stable/demo-apps-android.html, where the cards and screenshots work properly.

But, when browsing the code and looking at the .md file directly, it's broken.

@svekars do you know if there are any tricks we can do to show slightly different versions in the .md and rendered versions? @kirklandsign Maybe we should split this file into a plain .md file that points to the rendered website.

**Comment by dbort** [comment]
> @dbort Did you mean we should use the website MD as source and https://github.com/pytorch/executorch/blob/main/examples/demo-apps/android/ExecuTorchDemo/README.md point to that?

Yeah, or something like that. Instead of including the entire .md file in [`demo-apps-android.md`](https://github.com/pytorch/executorch/blob/f53aeeb2dcaa4240f4c87c6472097ce3e27c8b51/docs/source/demo-apps-android.md?plain=1#L1), `demo-apps-android.md` could contain most of this content directly, and `ExecuTorchDemo/README.md` could have a link to https://pytorch.org/executorch/stable/demo-apps-android.html, along with some basic descriptions. Or maybe there's a core piece that the website file includes from the example directory, but it doesn't include website-specific markup that won't render in github markdown.

**Comment by svekars** [comment]
I don't believe there is a way to hide the grid syntax on GitHub. If it's really critical to have this rendered on GitHub (which I don't think looks bad, btw) you might opt out to use regular lists instead for example. This is actually true for any extensions.  For example, autodoc-generated pages, like [this one](https://pytorch.org/executorch/main/export-to-executorch-api-reference.html), appear like [this](https://github.com/pytorch/executorch/blob/main/docs/source/export-to-executorch-api-reference.rst) on GitHub.
