### ISSUE TITLE
plan to support C[for most microcontrollers]?

### ISSUE THREAD

**Issue by mintisan** [pytorch/executorch#1061]
as title says...

**Comment by cccclai** [comment]
Is there any specific microcontroller you're interested in?

**Comment by dbort** [comment]
Although ExecuTorch uses C++, it doesn't use much of the standard library. As long as the microcontroller's toolchain supports building C++, it should be possible to write `extern "C"` wrappers to interact with it from pure C code.

We've already successfully built and run ExecuTorch on a handful of different microntrollers and DSPs. The main trick is to link against a version of the standard library that has exceptions and RTTI disabled.

As far as size goes, the runtime code is typically orders of magnitude smaller than the model itself.

**Comment by dbort** [comment]
Closing this because it's not directly actionable, but I'm happy to keep talking about this over in https://discuss.pytorch.org/c/executorch/42. Having a specific example of a target uC or toolchain would help focus the discussion.
Writing some common `extern "C"` wrappers could be a good project, too, but I'd also want to understand the requirements of the rest of the environment, so that the APIs match the needs.
