### ISSUE TITLE
[build Error initializing DaemonStateData] how to fix it

### ISSUE THREAD

**Issue by kris-himax** [pytorch/executorch#1117]
hi,

I reference [the tutorial](https://pytorch.org/executorch/stable/getting-started-setup.html#building-a-runtime) to install the buck2-x86_64-unknown-linux-musl.zst on my PC.
And I want to build 
```
/tmp/buck2 build //examples/portable/executor_runner:executor_runner --show-output
```
and face the build failed.

And I try to use `killall` reference from https://stackoverflow.com/questions/76771689/buck2-cant-create-inotify-watchers
and try build again.
But it is still build failed. Could somebody help me?

![Screenshot from 2023-10-31 13-44-29](https://github.com/pytorch/executorch/assets/87454575/ac9e9225-c7b8-4924-8a55-a474c0e4e49a)

OS: Linux Ubuntu 20.04.4 LTS x86_64 
buck2 version: 2023-07-18

Thanks,
Kris

**Comment by kris-himax** [comment]
I add the sudo and it can build success.
![Screenshot from 2023-10-31 16-45-49](https://github.com/pytorch/executorch/assets/87454575/06521167-89c4-44ab-b0a5-daca6b8ee5a7)

**Comment by Francis235** [comment]
Hi， following this related issue:https://github.com/coder/code-server/issues/628,  I have already increased {max_queued_events,max_user_instances,max_user_watches}, but I still have the issue:
(executorch) root@dev-aigc-5:/mnt/nfs/dev/worksapce/executorch# sysctl fs.inotify.{max_queued_events,max_user_instances,max_user_watches}
fs.inotify.max_queued_events = 999999
fs.inotify.max_user_instances = 999999
fs.inotify.max_user_watches = 5242880
(executorch) root@dev-aigc-5:/mnt/nfs/dev/worksapce/executorch# /tmp/buck2 build //examples/portable/executor_runner:executor_runner --show-output
Error initializing DaemonStateData

Caused by:
0: Error creating a FileWatcher for project root /mnt/nfs/dev/worksapce/executorch
1: Creating notify file watcher
2: OS file watch limit reached. about ["/mnt/nfs/dev/worksapce/executorch"]
Build ID: 6d237e90-089f-4210-ad00-3edaeaac79ae
Jobs completed: 0. Time elapsed: 0.0s.
BUILD FAILED
Any suggestions? thanks.
