### ISSUE TITLE
Is there a comprehensive list of pretrained models that are compatible with ExecuTorch?

### ISSUE THREAD

**Issue by hietalajulius** [pytorch/executorch#1328]
Could be useful to save folks time from struggling through converting the same models multiple times. I assume all e.g. torchvision models are compatible out-the-box for all backends?

**Comment by Jack-Khuu** [comment]
We have a list of example models stored here:  https://github.com/pytorch/executorch/tree/main/examples/models

cc:  @guangy10 for more context on externally supported model inventory

**Comment by guangy10** [comment]
Hi @hietalajulius, do you mean any pretrained model in OSS? We do not have such a list because it is changing everyday and it will be misleading. What we would like to know more is if you have tried any particular model and it's not working, we could help from there.

> struggling through converting the same models multiple times

Can you elaborate more? Which model and in what situation you want to convert it multiple times?

> all e.g. torchvision models are compatible out-the-box for all backends?

We currently don't have data covering all torchvisoin models. However, as @Jack-Khuu mentioned, we do have representative models added as examples. Models with similar type/architecture are likely just work of out-of-box. We will be happy to look into any particular issue if something doesn't work

**Comment by cbilgin** [comment]
This is indeed an active development area both internally and with the partners. Examples directory is the main source of truth and anything listed there should work out of the box. In general, you could expect cpu (and XNNPACK for that matter) to have better coverage as that's usually earlier in the development stage.

**Comment by hietalajulius** [comment]
Thank you so much for the detailed responses! I'm mainly looking for inspiration for a model to use in a tutorial/POC project, will pick one from the examples!

The reason I mentioned that a central place for converted models could be useful is that based on [previous experience](https://betterprogramming.pub/how-to-build-a-yolov5-object-detection-app-on-ios-39c8c77dfe58) people seem to struggle with the same things when trying to make models on mobile e.g NMS in YOLOv5 on CoreML in my case 👍 

Keep up the great work!
