### ISSUE TITLE
NaN values when doing inference

### ISSUE THREAD

**Issue by neverorfrog** [pytorch/executorch#1595]
Hi, I have implemented a demo similar to the executor_runner in C++ with an exported model of a small CNN trained on MNIST. The problem is, the inference spits out nan values whatever the input is. By the way, also an even simpler fully-connected 3-layer network would sometimes (depending on the random input) output very big or nan values. I believe it has something to do with numeric overflow, but I wouldn't know how to mitigate the problem, so I'm open to suggestions. I am aware the question is somehow vague, but I could give a bit more context if necessary. 
Thank you!

**Comment by mergennachin** [comment]
Hi @neverorfrog 

Thanks for trying out executorch and giving us feedback. 

One useful tool could be to use SDK for debugging.

There are several documentation, such as

https://pytorch.org/executorch/main/tutorials/sdk-integration-tutorial.html
https://pytorch.org/executorch/main/sdk-bundled-io.html 
https://pytorch.org/executorch/main/sdk-debugging.html

( Use the latest 'main' branch of the document https://pytorch.org/executorch/main/, as opposed to 'stable' document https://pytorch.org/executorch/stable/, since we have done various updates to the SDK since our last launch)

BundledProgram lets you specify expected final outputs of the model (usually the output from the eager mode in regular pytorch).

Inspector API lets you... inspect intermediate outputs of the model, so that you can narrow down which op is responsible.

cc @tarun292 , @Jack-Khuu , @Olivia-liu

**Comment by tarun292** [comment]
Also @neverorfrog feel free to share your .pte file here if you can.

**Comment by neverorfrog** [comment]
@mergennachin thank you for your thorough answer! I will check out these resources as soon as I can. Meanwhile @tarun292 here is the [.pte](https://github.com/pytorch/executorch/files/13999167/model.zip) file (it's zipped, I hope that does not break things).
Thank you both!

**Comment by mergennachin** [comment]
Hi @neverorfrog 

We will close this issue. Let us know if there's anything actionable from our side.

**Comment by neverorfrog** [comment]
@mergennachin sorry for the really late response, i actually found out that error was in how i prepared the inputs, not in the model itself
thanks again!
