### ISSUE TITLE
torch._ops.aten.bernoulli.p

### ISSUE THREAD

**Issue by utkusaglm** [pytorch/executorch#3832]
Hello,

When I call the **to_edge** function from **executorch.exir** for the swin_t torchvision model, I’m getting this error: `torch._export.verifier.SpecViolationError: Operator torch._ops.aten.bernoulli.p is not Aten Canonical.` Could you please help me with that?

The same operator error are also occurs with other swin and convnext models.

Best

**Comment by SS-JIA** [comment]
However, even if you skip the check it's likely that your model may not be able to execute because non ATen canonical operators are not currently implemented in ExecuTorch's kernel libraries. This means that to execute your model, you may need to provide an implementation for the `torch._ops.aten.bernoulli` operator.

I would recommend that you try to execute the model while skipping the check, and if you run into an error complaining that there is no kernel available for the `aten.bernoulli` operator:

1. Please open an issue to request that a implementation of `aten.bernoulli` be added to the portable kernel library
2. Alternatively, you can try to provide an implementation for the operator yourself. If you decide to go this route, let me know and I can provide some more details on how to do this.

**Comment by utkusaglm** [comment]
Thanks a lot for your quick reply to this issue and for the recommended solutions. @SS-JIA, the issue was related to eval mode. After I set the model to evaluation mode, it worked.
