### ISSUE TITLE
error running resnet50 with vulkan

### ISSUE THREAD

**Issue by Andrechang** [pytorch/executorch#3922]
I get and error running torchvision resnet50 with vulkan on android following the steps in the tutorial:
https://pytorch.org/executorch/main/build-run-vulkan.html

libc++abi: terminating due to uncaught exception of type vkcompute::api::Error: Exception raised from check_conv_args at executorch/backends/vulkan/runtime/graph/ops/impl/Convolution.cpp:229: (check_memory_layout_is(in, api::kChannelsPacked)) is false! 
Aborted

**Comment by digantdesai** [comment]
@SS-JIA can you help me with this?

**Comment by Andrechang** [comment]
more info to reproduce:
ANDROID_NDK=Android/sdk/ndk/27.0.11902837
Ubuntu=22.04

## To export model

`python export_resnet50.py`

## To create runner compile: main.cpp, managed_tensor.h 
```
cmake . -DCMAKE_INSTALL_PREFIX=cmake-android-out \
  -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
  -DANDROID_ABI=$ANDROID_ABI \
  -DEXECUTORCH_BUILD_EXTENSION_MODULE=ON \
  -DEXECUTORCH_BUILD_EXTENSION_DATA_LOADER=ON \
  -DEXECUTORCH_BUILD_VULKAN=ON \
  -DEXECUTORCH_BUILD_KERNELS_OPTIMIZED=ON \
  -DEXECUTORCH_BUILD_KERNELS_QUANTIZED=ON \
  -DPYTHON_EXECUTABLE=python \
  -Bcmake-android-out

cmake --build cmake-android-out -j16
```
## then send to android phone

**Comment by SS-JIA** [comment]
Hi @Andrechang, thank you for your interest in the Vulkan Delegate!

To address this issue, please try to export your model with the `"memory_layout_override"` compile option:

```
import executorch.backends.vulkan.serialization.vulkan_graph_schema as vk_graph_schema

compile_options = {"memory_layout_override": vk_graph_schema.VkMemoryLayout.TENSOR_CHANNELS_PACKED}
program: ExportedProgram = export(
    model, sample_inputs,
)
edge_program: EdgeProgramManager = to_edge(program)
edge_program = edge_program.to_backend(VulkanPartitioner(compile_options))
executorch_program = edge_program.to_executorch()
```

You may find an example of setting this option in the [`test_vulkan_delegate.py`](https://github.com/pytorch/executorch/blob/main/backends/vulkan/test/test_vulkan_delegate.py#L109-L124) file.

For some more context, the memory layout impacts how the tensor data is laid out in the GPU. The default memory layout is `TENSOR_WIDTH_PACKED` which is analogous to the `torch.contiguous` memory layout, and the `TENSOR_CHANNELS_PACKED` layout is analogous to the `torch.channels_last` memory layout. We recently started introducing alternative memory layouts and some operators are currently implemented only for certain memory layouts. Since memory layouts were introduced fairly recently memory layout management is currently a manual process. Apologies for the inconvenience!

In the future we plan to handle memory layout transitions automatically during the export process. Please try out the code snippet I pasted and let me know if there are further issues!

**Comment by Andrechang** [comment]
Thank you very much. It worked
