### ISSUE TITLE
where to use the sdpa_with_kv_cache_out function

### ISSUE THREAD

**Issue by l2002924700** [pytorch/executorch#4726]
hi,
could you please help me to tell where to use the sdpa_with_kv_cache_out(in the op_sdpa.cpp) function? I have chech the code many times, however I can;t find where to call the sdpa_with_kv_cache_out function.
thank you in advanced for your kind help

**Comment by JacobSzwejbka** [comment]
cc @kimishpatel

**Comment by kimishpatel** [comment]
Hello,
So the way it works is that, the non-out variant of the op, https://github.com/pytorch/executorch/blob/main/extension/llm/custom_ops/op_sdpa_aot.cpp#L100, is used in model code, like here https://github.com/pytorch/executorch/blob/main/examples/models/llama2/source_transformation/sdpa.py#L39. And then executorch export and lowering workflow replaced sdpa_with_kv_cache with sdpa_with_kv_cache.out op. Which is what is needed to be present at runtime. At runtime this op can be found because it is registered (meaning tells executorch runtime where to find the op) to executorch runtime here https://github.com/pytorch/executorch/blob/main/extension/llm/custom_ops/op_sdpa.cpp#L960
