### ISSUE TITLE
Add `POET (Private Optimal Energy Training)` to EXECUTORCH

### ISSUE THREAD

**Issue by rajveer43** [pytorch/executorch#997]
## motivation and pitch

POET enables the training of state-of-the-art memory-hungry **ML models on smartphones and other edge devices**. POET (Private Optimal Energy Training) exploits the twin techniques of integrated tensor rematerialization, and paging-in/out of secondary storage (as detailed in our paper at ICML 2022) to optimize models for training with limited memory. POET's Mixed Integer Linear Formulation (MILP) ensures the solutions are provably optimal!

## implementation available 

https://github.com/ShishirPatil/poet
https://arxiv.org/abs/2207.07697

**Comment by JacobSzwejbka** [comment]
This is a cool paper. Ill pass it around to the rest of the team to discuss.

**Comment by rajveer43** [comment]
@JacobSzwejbka, Looking forward to hearing from you

**Comment by JacobSzwejbka** [comment]
We read through the paper today. I think its a good one! I like that its predominantly AoT planner work. That should make it compose nicely with the rest of stuff going on in export and exir. My initial thoughts while looking at this are 
1. We need a stronger story from Export on what the training surface is in export in order to make any meaningful design progress on training in ExecuTorch. 

2. In ExecuTorch there will be discussions around how exactly we want to support training. Naively something like poet would require some intrusive changes in the ET instruction set and AoT to get working out of the box with what we have today, but if we got clever about how we formed our graphs AoT we may be able to just fully compose this on top of what exists today allowing inference only use cases (the much more common one) to avoid paying any cost.

3. Training is not an immediate priority for ExecuTorch. We want to get to it some time next year, but our immediate focus is making sure we tell a really compelling inference story. Once we get started on training I would imagine our first release would focus primarily on just getting it running and then if theres sufficient user interest we could look into optimization schemes like poet on top.

Thanks for submitting the issue though and sharing the paper. Its really useful information to have as we start more detailed planning for training on ExecuTorch.

**Comment by Gasoonjia** [comment]
Chat with @JacobSzwejbka, POET is a long-term goal and we do not have specific plan in the foreseen future. Close it for now and will reopen it once we have clear road map for supportive.

**Comment by rajveer43** [comment]
> Chat with @JacobSzwejbka, POET is a long-term goal and we do not have specific plan in the foreseen future. Close it for now and will reopen it once we have clear road map for supportive.

Hi, @Gasoonjia 

Thanks for checking out the POET paper. Appreciate your positive feedback on the AoT planner work.

I understand the importance of a strong training surface in Export for ExecuTorch. Your insights on adjustments in the ET instruction set and AoT integration make sense.

Agree with prioritizing inference first, then exploring POET optimizations based on user interest in subsequent releases.

Closing the issue aligns with the long-term goal perspective. Looking forward to revisiting it with a clear roadmap.

Thanks for considering `POET` in the `ExecuTorch` context.
